[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
packages = ["nodejs-18_x", "npm-8_x"]

[build.nixpacksConfig.phases.setup]
cmds = ["npm ci"]

[build.nixpacksConfig.phases.build]
cmds = ["npm run build"]

[deploy]
startCommand = "caddy run --config /etc/caddy/Caddyfile"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"