[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = [
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn perfumes_project.wsgi:application --host 0.0.0.0 --port $PORT'

[variables]
PORT = '8000'